version: '3.3'

volumes:
  postgresql-data:
    driver: local
  elasticsearch-data:
    driver: local
  redis-data:
    driver: local

networks:
  overnet:
    driver: overlay
    attachable: true

services:
  postgresql:
    image: postgres:9.6.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - overnet
  redis:
    image: redis:3.2.11-alpine
    ports: 
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - overnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1 
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - overnet
