version: '3.3'
services:
  postgresql:
    image: postgres:9.6.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=security
  redis:
    image: redis:3.2.11-alpine
    ports: 
      - "6380:6380"
  memcached:
    image: memcached:1.5.1-alpine
    ports:
      - "11211:11211"
